config/routes.rb
Rails.application.routes.draw do

  get 'charges/create'
  devise_for :users

  get 'welcome/index'
  get 'welcome/about'
  root 'welcome#index'
  resources :users do
    member do
      post :downgrade
    end
  end
  resources :wikis

  resources :charges, only: [:new, :create]
  resources :wikis do
  resources :collaborators, only: [:new, :create, :destroy]
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

  @user_options = User.all.map { |u| [ u.email, u.id] }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # validates private: false
  after_update :publish_all
   private
    def publish_all
     if user.role == 'standard'
       user.wikis.where(private: true) do |makepub|
         makepub.update_attributes(private: false)
  end

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :collaborators
  has_many :wikis, through: :collaborators

  before_save { self.email = email.downcase }
   after_initialize { self.role ||= :standard }

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  enum role: [:standard, :admin, :premium]

  private

  def send_user_emails
    UserMailer.new_user(self).deliver_now
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
after_initialize :initialize_role

   private
   def initialize_role
     self.private = false if self.private.nil?
   end

  validates :title, presence: true
  belongs_to :user, optional: true
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :visible_to, -> (user) do
    return all if user.premium? || user.admin?
    where(private: [false, nil])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


   protect_from_forgery with: :exception

 before_action :configure_permitted_parameters, if: :devise_controller?
 before_action :authenticate_user!

 protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation) }
  end

  include Pundit
  protect_from_forgery
 end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
    @user = current_user

    #Creates a Stripe Customer object, for associating with the charge.
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )


  # Payment being made
  charge = Stripe::Charge.create(
    customer: customer.id,
    amount: 15_00,
    description: "Upgrade to Premium Membership - #{current_user}",
    currency: 'usd'
  )

    @user.update_attributes(role: 'premium')


  flash[:notice] = "Thanks for the payment, #{current_user.email}! You can now create and edit private wikis."
  redirect_to root_path

  # Stripe will send back CardErrors, with friendly messages when something goes wrong.
  # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
       description: "Premium Membership - #{current_user}",
      amount: 15_00
    }
  end
  private

  def upgrade_user_role
   @user.role = 'premium'
  end

end

app/controllers/collaborator_controller.rb
class CollaboratorsController < ApplicationController

  def new
    @collaborator = Collaborator.new
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find_by(email: params[:email])
    @collaborator = @wiki.collaborators.build(user_id: @user.id)

    if @collaborator.save
      flash[:notice] = "Collaborator was added to this wiki."
      redirect_to @wiki
    else
      flash[:error] = "Collaborator was not added. Please try again."
      render :show
    end
   end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaboration = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator was removed from this wiki."
      redirect_to @wiki
    else
      flash[:error] = "Collaborator was not removed. Please try again."
      render :show
    end
   end

  private

  def collaboration_params
    params.require(:collaborator).permit(:user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
   def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name =                  params[:user][:name]
    @user.email =                 params[:user][:email]
    @user.password =              params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Blocipedia, #{@user.name}!"
      redirect_to root_path
    else
      flash[:error] = "There was an error creating your account. Please try again."
      render :new
    end
        @user_wikis = @user.wikis.where(private: true)

    @user_wikis.each do |makepub|
      makepub.update_attributes(private: false)
    end
 end

 def downgrade
  @user = User.find(params[:id])
  @user.role = 'standard'

  if @user.save
    flash[:notice] = "You've been downgraded to standard. Your private wikis are now public."
    redirect_to :back
  else
    flash[:error] = "There was an error creating your account. Please try again."
    redirect_to :back
  end
end

  def index
    @users = User.all
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!, except: [ :index, :show ]

  after_action :verify_authorized, :except => :index

  def index
    @wikis = policy_scope(Wiki)

  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaboration = @wiki.collaborators.new
    authorize @wiki
  end

  def new
    @user = current_user
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @user = current_user
    @wiki = current_user.wiki.build(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash[:error] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @collaborator = Collaborator.new
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:error] = "Error saving wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash[:error] = "There was an error deleting the wiki."
      render :show
    end
  end

 private

  def wiki_params
     params.require(:wiki).permit(:title, :body, :private, :user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
   else
      content_tag :div, capture(&block), class: 'form-group'
    end
 end

 def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4> Upgrade to Premium Membership </h4>
    <div>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
    </div>
<% end %>

app/views/collaborators/_form.html.erb
<% if @wiki.user_id == current_user.id || current_user.admin? %>
		<div class="form-group">
			<%= hidden_field_tag(:wiki_id, value: @wiki.id) %>
			<%= label_tag(:email, "Collaborator email") %> <br>
			<%= f.select :user_id, options_from_collection_for_select(User.all, "id", "email") %>
		</div>
<% end %>

app/views/collaborators/_users.html.erb
<h4>Collaborators</h4>
<ul>
	<% @wiki.collaborators.each do |collaborator| %>
		<li>
			<%= collaborator.user.name %> <%= link_to "", "/wikis/#{@wiki.id}/collaborators/#{collaborator.id}", method: :delete, class: 'glyphicon glyphicon-remove' %>
		</li>
	<% end %>
</ul>

app/views/collaborators/new.html.erb
<h1>Add Collaborator</h1>

<%= form_for [@wiki, @collaboration] do |f| %>

  <% if @wiki.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(@wiki.errors.count, "error") %>.</h4>
       <ul>
         <% @wiki.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
  <% end %>

  <%= form_group_tag(@wiki.errors[:user]) do %>
    <%= f.label :user %>
    <%= f.select :user_id, options_from_collection_for_select(User.all, "id", "email") %>
  <% end %>

  <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li> <%= link_to "Home", welcome_index_path %> </li>
      <li> <%= link_to "About", welcome_about_path %> </li>
      <li> <%= link_to "Wikis", wikis_path %> </li>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
        Signed in as: <strong> <%= current_user.email %> </strong> |
        <%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %> |

        <% if current_user.role == 'standard' || current_user.role == 'admin' %>
        <%= link_to "Upgrade to Premium", new_charge_path %>
        <% else %>
        <%= link_to "Downgrade to Standard", edit_user_registration_path %>
        <% end %>

        <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
    <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
    <% end %>

    <%= yield %>
  </div>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1> Blocipedia Users </h1>

<div class="row">
  <div class="col-md-8">
    <% @users.each do |user| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
             Email: <%= user.email %> <br>Role:  <%= user.role.capitalize %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h2> Sign Up </h2>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <h4> <%= pluralize(@user.errors.count, "error") %>. </h4>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form_group_tag(@user.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
    <% end %>

    <%= form_group_tag(@user.errors[:email]) do %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
    <% end %>

    <%= form_group_tag(@user.errors[:password]) do %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
    <% end %>

    <%= form_group_tag(@user.errors[:password_confirmation]) do %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
    <% end %>

    <div class="form-group">
      <%= f.submit "Sign Up", class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Blocipedia</h1>
<p>Wiki made as a test</p>

app/views/welcome/index.html.erb
<br>
<div class="heading">
  <h1> Blocipedia </h1>
  <p> Use Blocipedia to create and edit wikis about meaningful topics. </p>
  <p>
    <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2> Create all kinds of wikis for free: </h2>
    <%= link_to "Free Plan", new_user_path, class: 'btn btn-info' %>
  </div>

  <div class="col-md-4">
    <h2> Or create private wikis!</h2>
    <%= link_to "Premium Plan", new_charge_path, class: 'btn btn-info' %>
  </div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>

  <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div> 
</div>
</div>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>

  <%= f.submit "Save", class: 'btn btn-success' %>

<% end %>
</div>

app/views/wikis/edit.html.erb
<h1> Edit Wiki </h1>

<div class="row">
    <div class="col-md-4">
      <p> Rules for Wikis : </p>
      <ul>
        <li> No spamming of innapropriate content. </li>
        <li> Dont make a proofreading error! </li>
        <li> No duplicate posts please. </li>
      </ul>
    </div>
      <%= render partial: 'wikis/form', locals: { f: f } %>

      <% if @wiki.private %>
			   <%= render partial: 'collaborators/form', locals: { f: f } %>
		  <% end %>

      <%= f.submit "Save", class: 'btn btn-success' %>
      <% end %>
    </div>
</div>

app/views/wikis/index.html.erb
<h1> Wikis </h1>

<div class="row">
    <div class="col-md-8">
      <% @wikis.each do |wiki| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to markdown(wiki.title), wiki %>
            </h4>
            <small>
              <%= markdown(wiki.body) %>
            </small>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
</div>

app/views/wikis/new.html.erb
<h1> New Wiki </h1>

<div class="row">
    <div class="col-md-4">
      <p> Rules for Wikis : </p>
      <ul>
        <li> No spamming of innapropriate content. </li>
        <li> Dont make a proofreading error! </li>
        <li> No duplicate posts please. </li>
      </ul>
    </div>
    <div class="col-md-8">
     <%= render partial: 'form' %>
    </div>
</div>

app/views/wikis/show.html.erb
<div>
<h1>
  <%= markdown(@wiki.title) %> <br>
  <small>
    submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @user_email %>
  </small>
</h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>

  <div class="col-md-4">
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <% if (current_user.role == 'admin' && @wiki.private == true) || (current_user.role == 'premium' && @wiki.private == true && @wiki.user_id == current_user.id) %>
        <%= link_to "Add Collaborator", new_wiki_collaborator_path(@wiki), class: 'btn btn-info' %>
      <% end %>
      <%= link_to "Delete Post", [@wiki], method: :delete , class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
      </div>
  </div>
  <% if @wiki.private %>
        <% if Collaborator.exists?(wiki_id: @wiki) %>
          <%= render partial: 'collaborators/users' %>
        <% end %>
      <% end %>